// export const PLAYERS_ERROR = 'PLAYERS_ERROR';
// export const SET_LOADING = 'SET_LOADING';
export const ADD_PLAYER = 'ADD_PLAYER';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const UPDATE_PLAYER_NAME = 'UPDATE_PLAYER_NAME';
