export const ADD_PLAYER = 'ADD_PLAYER';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const UPDATE_PLAYER_NAME = 'UPDATE_PLAYER_NAME';
export const DELETE_PLAYER = 'DELETE_PLAYER';

export const MIX = 'MIX';
export const DISTRIBUTE = 'DISTRIBUTE';
export const PREPARE_BOARD_CARDS = 'PREPARE_BOARD_CARDS';
export const SET_GAME_ROUND = 'SET_GAME_ROUND';
